language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install -r ci_requirements.txt --use-mirrors

script: nosetests tests --with-cov -v 
after_success:
    - coveralls
