language: python
python:
    - "2.6"
    - "2.7"

install:
    - pip install . -e --use-mirrors
    - pip install -r requirements.txt --use-mirrors

script: nosetests --with-coverage 

after_success:
  - coveralls

